<?php
// pages/reports_pdf.php
// Make sure Composer's autoload is available and dompdf is installed (composer require dompdf/dompdf)
require_once '../dompdf/vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

ini_set('memory_limit', '512M'); // you may increase if images are huge
set_time_limit(60);

$raw = file_get_contents('php://input');
if (!$raw) {
    http_response_code(400);
    echo "No input received.";
    exit;
}

$data = json_decode($raw, true);
if (!is_array($data) || empty($data['image'])) {
    http_response_code(400);
    echo "Invalid payload. 'image' required.";
    exit;
}

$imageData = $data['image']; // data:image/png;base64,...
// strip header if present
if (preg_match('/^data:(image\/\w+);base64,/', $imageData, $m)) {
    $imageData = substr($imageData, strpos($imageData, ',') + 1);
}
$imageBinary = base64_decode($imageData);

if ($imageBinary === false) {
    http_response_code(400);
    echo "Invalid base64 image data.";
    exit;
}

// Convert logo image to base64
$logoPath = __DIR__ . "/../assets/img/primary_logo.svg"; // change to .svg or .jpg if needed
if (file_exists($logoPath)) {
    $logoData = file_get_contents($logoPath);
    $logoBase64 = 'data:image/' . pathinfo($logoPath, PATHINFO_EXTENSION) . ';base64,' . base64_encode($logoData);
} else {
    $logoBase64 = ''; // fallback if logo missing
}

$filters = $data['filters'] ?? [];

// Handle conditional filters
$allTime = !empty($filters['allTime']);
$fromDate = htmlspecialchars($filters['fromDate'] ?? '—');
$toDate   = htmlspecialchars($filters['toDate'] ?? '—');
$serviceType = !empty($filters['serviceType']) ? htmlspecialchars($filters['serviceType']) : 'All (Appointments, Walk Ins)';

// If all time is true, ignore date
$dateRange = $allTime ? 'All Time' : "$fromDate → $toDate";

// Build filter details HTML (aligned right)
$filterDetails = '
    <div style="text-align:right; line-height:1.6;">
        <div><b>Date Range:</b> ' . $dateRange . '</div>
        <div><b>Service Type:</b> ' . $serviceType . '</div>
    </div>
';

// Use a table for perfect alignment in Dompdf
$filterHtml = '
<table width="100%" style="border-bottom:1px solid #ccc; padding-bottom:8px; font-size:12px;">
    <tr>
        <td style="width:40%; vertical-align:middle;">
            <img src="' . $logoBase64 . '" alt="Logo" style="height:60px;">
        </td>
        <td style="width: 300px; margin-left: 100%; vertical-align:middle;">
            <div><b>Date Range:</b> ' . $dateRange . '</div>
            <div><b>Service Type:</b> ' . $serviceType . '</div>
        </td>
    </tr>
</table>
';

// Build HTML for dompdf. We embed the image as base64 to avoid saving files.
$embedded = 'data:image/png;base64,' . base64_encode($imageBinary);

$html = '
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Reports</title>
<style>
    body { 
    font-family: DejaVu Sans, Arial, sans-serif; 
    margin: 18px; 
    }
    .header { 
    margin-bottom: 10px; 
    }
    .filters { 
    margin-bottom: 10px; 
    font-size: 12px; 
    }
    .img-wrap { 
    width: 100%;
    text-align:
    center; 
    }
    .img-wrap img {
    max-width: 100%;
    max-height: 100%;
    width: auto;
    height: auto;
    display: block;
    margin: 0 auto;
    }

</style>
</head>
<body>
<div class="header">
    <div class="filters">' . $filterHtml . '</div>
</div>
<br>
<div class="img-wrap">
    <img src="' . $embedded . '" alt="dashboard" />
</div>
    <!-- Text Column -->
    <div style="text-align:right; font-size:11px; color:#555;">
        This report is generated by <br><b>CabTech Auto Services</b>
    </div>
</body>
</html>
';

// Setup dompdf
$options = new Options();
$options->set('isRemoteEnabled', true);
$dompdf = new Dompdf($options);
$dompdf->setPaper('a4', 'landscape');

$dompdf->loadHtml($html);
$dompdf->render();

// Output PDF as stream (the client JS expects a PDF blob)
$pdfOutput = $dompdf->output();

header('Content-Type: application/pdf');
header('Content-Length: ' . strlen($pdfOutput));
header('Content-Disposition: attachment; filename="reports.pdf"');
echo $pdfOutput;
exit;
